version: '3.7'

services:
  frontend:
    container_name: react-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    stdin_open: true
    command: npm start
